---
layout:     post
title:      python基础-错误处理
date:  2017-10-19
keywords:   python基础
category:   java
tags:   [python,python基础]
---
try..except...finally  
```
try:
    print('try...')
    r = 10 / 0
    print('result:', r)
except ZeroDivisionError as e:
    print('except:', e)
else:  //当没有捕获异常的时候执行
    print('no error!')
finally:
    print('finally...')
print('END')
```

Python 的错误其实也是class，所有的错误类型都继承自BaseException  

记录错误
---
使用logging日志  
```
import logging
def foo(s):
    return 10 / int(s)
def bar(s):
    return foo(s) * 2
def main():
    try:
        bar('0')
    except Exception as e:
        logging.exception(e)
```
抛出错误
---
**raise**  
```
class FooError(ValueError):
    pass
def foo(s):
    n = int(s)
    if n==0:
        raise FooError('invalid values: %s' % s)
    return 10 / n

try:
    print(int(foo('1')))
except BaseException as e:
    print(e)
```
